### ISSUE TITLE
Uninitialized constant Uber::Options when updating to 4.1.6

### ISSUE THREAD

**Issue by wintersolutions** [trailblazer/cells#445]
I updated cells from 4.1.5 to version 4.1.6. When I run my specs now I get the error `Uninitialized constant Uber::Options (NameError)`. The full stacktrace (anonymized) is found below.

Currently my workaround is to not update cells.

**Note**: This issue was filed under https://github.com/trailblazer/trailblazer/issues/175 first until I found out that cells is the culprit here.

Relevant gems and their versions:

* trailblazer 2.0.3
* bundler 1.13.6
* cells-rails 0.0.7
* cells 4.1.6
* cells-hamlit 0.2.0
* trailblazer-cells 0.0.3
* trailblazer-loader 0.1.0
* trailblazer-operation 0.0.12
* trailblazer-rails 1.0.2
* uber 0.1.0

```
/home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/reform-2.2.3/lib/reform/form/populator.rb:12:in `initialize': uninitialized constant Uber::Options (NameError)
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/reform-2.2.3/lib/reform/form.rb:25:in `new'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/reform-2.2.3/lib/reform/form.rb:25:in `property'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/reform-rails-0.1.7/lib/reform/form/active_model.rb:30:in `property'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/reform-rails-0.1.7/lib/reform/form/active_model/form_builder_methods.rb:15:in `property'
	from /home/foo_user/projects/foo_project/app/concepts/base_contract.rb:2:in `<class:BaseContract>'
	from /home/foo_user/projects/foo_project/app/concepts/base_contract.rb:1:in `<top (required)>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-rails-1.0.2/lib/trailblazer/rails/railtie.rb:19:in `block in load_for'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `block in load_files'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `each'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `load_files'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:38:in `call'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-rails-1.0.2/lib/trailblazer/rails/railtie.rb:19:in `load_for'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-rails-1.0.2/lib/trailblazer/rails/railtie.rb:11:in `load_concepts'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/trailblazer-rails-1.0.2/lib/trailblazer/rails/railtie.rb:31:in `block (2 levels) in <class:Railtie>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:396:in `instance_exec'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:396:in `block in make_lambda'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:546:in `catch'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:546:in `block in default_terminator'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:454:in `block in call'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:454:in `each'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:454:in `call'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_prepare_callbacks'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/activesupport-5.0.1/lib/active_support/reloader.rb:87:in `prepare!'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/foo_user/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
	from /home/foo_user/projects/foo_project/config/environment.rb:5:in `<top (required)>'
	from /home/foo_user/projects/foo_project/spec/rails_helper.rb:6:in `require'
	from /home/foo_user/projects/foo_project/spec/rails_helper.rb:6:in `<top (required)>'
	from /home/foo_user/projects/foo_project/spec/concepts/base_operation_spec.rb:1:in `require'
	from /home/foo_user/projects/foo_project/spec/concepts/base_operation_spec.rb:1:in `<top (required)>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/bin/rspec:22:in `load'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/bin/rspec:22:in `<main>'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/bin/ruby_executable_hooks:15:in `eval'
	from /home/foo_user/.rvm/gems/ruby-2.3.3@foo_project/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by apotonick** [comment]
The problem is Reform 2.2.3, and not Cells.

**Comment by wintersolutions** [comment]
Damn, there it is on the first line of the stacktrace

**Comment by apotonick** [comment]
You can now upgrade to Reform 2.2.4, which doesn't use `uber` anymore.
